### ISSUE TITLE
Open Sources in BDV kills Fiji

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#108]
Hi,

- open a few xml/h5
- select all sources
- right click -> show sources
- **Mixed Projector**
- **adjust Contrast + adjust View on Source**
- freezes whole Fiji

bold points are necessary to create the behaviour, otherwise it does the job.

**Comment by NicoKiaru** [comment]
Ok, to let you know, some freeze bugs are to be expected with the new UI. Most probably, they will have to be solved by @tpietzsch in bdv-core. 

What I'll do for these freeze is try to find a minimal example to give to Tobias.

And thanks so much for testing!

**Comment by NicoKiaru** [comment]
Freezes with 'adjust Contrast' AND/OR 'adjust View on Source'.

**Comment by NicoKiaru** [comment]
This one I could do, thanks a lot for the detailed description, that made it easy!

https://github.com/bigdataviewer/bigdataviewer-playground/commit/00e74b0eb9e912a7835204ff149754a9a78651ee

**Comment by tpietzsch** [comment]
@NicoKiaru 

```java
final List< SourceAndConverter > visibleSacs = bdvHandle.getViewerPanel().state().getVisibleAndPresentSources().stream().collect(Collectors.toList());
```
This list will probably not be sorted in the order of sources in the state, because it is obtained from a set. To get a sorted list you can do it like this
```java
ViewerState state = bdvHandle.getViewerPanel().state();
synchronized( state )
{
	final List< SourceAndConverter< ? > > visibleSacs = new ArrayList<>( state.getVisibleAndPresentSources() );
	visibleSacs.sort( state.sourceOrder() );
}
```

**Comment by NicoKiaru** [comment]
Thanks @tpietzsch ! I think it works because even if the order is random, I'm keeping the same order for the linked projection mode thanks to a `HashMap<SourceAndConverter, String>`. I think the projection ultimately do not depend on the order of the sources.

But - re-looking at the code I see that I have some deprecated code that I need to update for this projector: the good thing is, the code will be much compact and easier to understand with the new core. So thank you for that! 

For the record, there a class which was hiding the indexing logic, and with the new bdv-core, it decreased a lot in terms of lines of code (https://github.com/bigdataviewer/bigdataviewer-playground/commit/3439fc9fd43550de69ed30c4886886f368b1e837)
