### ISSUE TITLE
UI elements: consistency, naming, comments...

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#130]
Hi,

this issue is dedicated to feedback on UI elements. I try to work my way systematically through the menus ;-)

**Comment by martinschorb** [comment]
```Bdv```:
- can we agree on using BDV (all caps) whenever we use the abbreviation?

- ```Show Sources``` , ```Remove Sources from BDV```, ```Set Timepoints```, ```Show sources in multiple...```: The selector boxes all have the variable names as descriptors. This is confusing to the user. Can we unify this and call a selection of sources "Source(s)", a selection of BDV windows "BDV windows" instead of ```src_in```, ```sacs```, ```BdvHs```?
You have already done this very nicely in ```Synchronize Windows``` ;-)
(I would offer to do this myself if you give me some hint where in the code I can find those dialog elements)

**Comment by NicoKiaru** [comment]
> I would offer to do this myself if you give me some hint where in the code I can find those dialog elements

If you are motivated, you're very welcome. But how familiar are you with java dev in an IDE, maven git and all this stuff ? Because that's a time consuming part. 

For hints : all the scijava commands are located in subpackages of [sc.fiji.bdvpg.scijava.command](https://github.com/bigdataviewer/bigdataviewer-playground/tree/master/src/main/java/sc/fiji/bdvpg/scijava/command)

If you look at the ortho viewer command, you will notice a `label` field in `@Parameter` annotations:

https://github.com/bigdataviewer/bigdataviewer-playground/blob/master/src/main/java/sc/fiji/bdvpg/scijava/command/bdv/BdvOrthoWindowCreatorCommand.java

That's what you should add to modify the displayed name of the parameters when they appear in the UI.

This [`Show Sources`](https://github.com/bigdataviewer/bigdataviewer-playground/blob/master/src/main/java/sc/fiji/bdvpg/scijava/command/bdv/BdvSourcesAdderCommand.java) command has no `label` field, and thus the name of the variable is displayed instead.

**Comment by martinschorb** [comment]
> If you are motivated, you're very welcome. But how familiar are you with java dev in an IDE, maven git and all this stuff ? Because that's a time consuming part.

I was thinking of avoiding to go through all of this and simply update the ```labels``` directly in a git branch of the source. You could then simply merge it without interfering with your code changes and I wouldn't have to worry about the deployment.

**Comment by NicoKiaru** [comment]
If you already have in mind how to do it, please do, no issue.

But otherwise we can plan an hour to put this in place in your computer. If the goal is clear, I think one hour is sufficient and then you can test easily and directly your modifications.

As you wish

**Comment by martinschorb** [comment]
```Sources```:

- I would collect all sample sources in a single menu item. I guess these are valuable for development purposes, but the users won't need them regularly.

- ```Export``` ```Current View```. Wouldn't this be more of a ```Screenshot``` type activity that should appear under ```BDV```?

- Maybe all ```Export```options should be grouped into one sub-menu.

- ```Transform``` -> ```Center Source``` does not work in Z (moves edge to 0 instead of center)

**Comment by martinschorb** [comment]
```SpimDataset```:

- I know this is the technical name of a dataset, but as we now deal with very different types of microscopy, could we just call it "Dataset" instead everywhere in the UI?

- ```Open XML/HDF5 files``` I would just call it "Open BDV-XML File(s)" because we also support other data file formats (n5, tif, your slides...)

**Comment by martinschorb** [comment]
Should I just start modifying some labels in a branch, or do you want to discuss general concepts first to decide on the precise naming of labels together?

**Comment by NicoKiaru** [comment]
> `Sources`:
> 
>   I would collect all sample sources in a single menu item. I guess these are valuable for development purposes, but the users won't need them regularly.

That's good to have for tutorials and scripting demos. Personally I'm always annoyed when there's nothing available on the spot to test a promising plugin. Sample sources in ImageJ1 is very useful for instance. 

We could actually move them here, this requires to change the `menuPath` field in the `Command`. For instance:

`@Plugin(type = Command.class, menuPath = "File>Open Samples>Sample BDV Source")`

instead of the current line

https://github.com/bigdataviewer/bigdataviewer-playground/blob/721cd1fa1387f6f7575a692adc6763a735a28c90/src/main/java/sc/fiji/bdvpg/scijava/command/source/SampleSourceCreatorCommand.java#L14

Maybe we can move them here ? 

> 
>     * `Export` `Current View`. Wouldn't this be more of a `Screenshot` type activity that should appear under `BDV`?

Right. I think this one is in another repo, it's in bigdataviewer-biop-tools. I will deal with it. I can either move it in bdv-playground or let it on biop tools. Usually the code is not as clean in biop tools and do not follow exactly the rules we set in the playground. Anyway it would be good to have a fixed set of rules for he denomination, and we can then apply these rules for repositories that complement bdv-playground.

> 
>     * Maybe all `Export`options should be grouped into one sub-menu.
> 

Yes

>     * `Transform` -> `Center Source` does not work in Z (moves edge to 0 instead of center)

OK, that's a separate issue, can you open it ? I think @tischi mentioned it in gitter or somewhere else.

**Comment by NicoKiaru** [comment]
> 
> 
> `SpimDataset`:
> 
>    I know this is the technical name of a dataset, but as we now deal with very different types of microscopy, could we just call it "Dataset" instead everywhere in the UI?

Yes, or rather `BDV Dataset` ? Dataset is too generic, this could create some confusions. Or another prefix or suffix.

> 
>     `Open XML/HDF5 files` I would just call it "Open BDV-XML File(s)" because we also support other data file formats (n5, tif, your slides...)

That's right.

**Comment by martinschorb** [comment]
> Yes, or rather `BDV Dataset`

I like that!

**Comment by NicoKiaru** [comment]
> Should I just start modifying some labels in a branch, or do you want to discuss general concepts first to decide on the precise naming of labels together?

Please do as you think it's the most efficient for you. Personally I find more efficient if you propose something first, which looks fully consistent. Then we can test it and comment / amend. The downside is that we should not be afraid to modify several times the same thing.

My only two recommendations at this point would be:

* When you rename `Command` in the menu, try avoiding names which are too generic (like `Open Dataset`: if we have too generic names, several commands can have the same names as other fiji plugins. And it's a problem because then Macro Scripting will not function. One way to ensure unicity is to always add an identifier prefix or suffix in the Command names. This can be a static String variable, like the one we have to position Command in the FIJI menuPath. `BDVPG` would do but it's a bit ugly. Note that it's used in CLIJ for instance. All plugins starts with CLIJ_doStuff.

* try to maintain the structure (not the names):
** Bdv
** Sources
** SpimDataset

`Bdv` contains Commands which require at least an open window
`Sources` contains Commands which act on Sources independently of a display, or of their belonging to a SpimDataset.
`SpimDataset` Command commands which involve at least the reference to a dataset

I  think these are three well separated classes, and this structure also reflects how it's shaped in the code. But I might be wrong and maybe there are non obvious places for some Commands.

**Comment by martinschorb** [comment]
Hi,

I found that the "All Sources" is gone from the source list.
I was always using that, because it was a way to easily provide me with the name of the ViewSetups (which has a meaning in my scenario).

Now it only shows the SpimDataN directories which makes it hard to find specific Sources. 
Could you rename those directories by something meaningful?

Right now only ViewSetups have a "name" tag. 

**Option 1:**

So one option would be to display something like the common prefix of the names of the viewsetups...

If I have the viewsetup names:
- a1.tif_tile0_t0
- a1.tif_tile1_t0
- a1.tif_tile0_t1
- ...

I would call the SpimDataN "a1.tif"

**Option 2**
Another option would be to introduce a new tag `name` in the top-level `SpimData` description in the xml and show this if available.

**Comment by NicoKiaru** [comment]
> 
> 
> Hi,
> 
> I found that the "All Sources" is gone from the source list.
> I was always using that, because it was a way to easily provide me with the name of the ViewSetups (which has a meaning in my scenario).

I agree and this was useful -> I'll restore it

> 
> Now it only shows the SpimDataN directories which makes it hard to find specific Sources.
> Could you rename those directories by something meaningful?

Yes we should. It's just not super easy to make it properly because there's no convenient place to name it. Your xml tag may be an option but I don't know how to do it yet.

> 
> Right now only ViewSetups have a "name" tag.
> 
> **Option 1:**
> 
> So one option would be to display something like the common prefix of the names of the viewsetups...
> 
> If I have the viewsetup names:
> 
>     * a1.tif_tile0_t0
> 
>     * a1.tif_tile1_t0
> 
>     * a1.tif_tile0_t1
> 
>     * ...
> 
> 
> I would call the SpimDataN "a1.tif"
> 
> **Option 2**
> Another option would be to introduce a new tag `name` in the top-level `SpimData` description in the xml and show this if available.

**Comment by martinschorb** [comment]
Cool. Obviously the file name is a simple but good choice.

Right now it is displaying the full path though. Could you just use the file base name even without extension? I think this would be the ideal caption for it.

**Comment by NicoKiaru** [comment]
I've made it simple for now, but that needs some improvements. Note that it also works for remote server. I can probably look for the last '/' caracter and remove what's before

**Comment by martinschorb** [comment]
I found this...
**File.getName()**
```
import java.io.File;

public class JavaFileDirNameBaseName {
    public static void main(String[] args) {
    File theFile = new File("../foo/bar/baz.txt");
    System.out.println("Dirname: " + theFile.getParent());
    System.out.println("Basename: " + theFile.getName());
    }
}
```

**Comment by NicoKiaru** [comment]
Yes! The little detail is that I'm dealing with a String only, and this string can be either a File Path or a URL, in case of a dataset present on a BigDataServer.

The line of code which sets the name is here : https://github.com/bigdataviewer/bigdataviewer-playground/blob/c65556107b7b0f03113f1e00a6a20b4eb9e30602/src/main/java/sc/fiji/bdvpg/spimdata/importer/SpimDataFromXmlImporter.java#L38

**Comment by martinschorb** [comment]
I see, also for the sample datasets, it reverts back to `SpimData`

I just created a local branch for renaming UI items. Shall we use `BDVDatasets` as general term instead of SpimData? Then this would be the first change I try to consistently put everywhere.

**Comment by NicoKiaru** [comment]
BDVDataset or BDVDatasets ?

**Comment by martinschorb** [comment]
One  BDVDataset. That's also how I would call the Menu

**Comment by martinschorb** [comment]
> Yes! The little detail is that I'm dealing with a String only, and this string can be either a File Path or a URL, in case of a dataset present on a BigDataServer.
> 
> The line of code which sets the name is here :
> 
> https://github.com/bigdataviewer/bigdataviewer-playground/blob/c65556107b7b0f03113f1e00a6a20b4eb9e30602/src/main/java/sc/fiji/bdvpg/spimdata/importer/SpimDataFromXmlImporter.java#L38

Right here you do use a file object. So you could in this case really just use the `getName()`  instead (l.16) to get your `BDVDataset` caption.

**Comment by martinschorb** [comment]
Hmm, OK I see. You need the absolute path to load the data...

**Comment by NicoKiaru** [comment]
That's solvable. The way we deal with lacking properties of some object is to create a `Map<MyObject, Object>` to associate some data.

We needed a:
* `Map<SourceAndConverter, Object>`
* `Map<BdvHandle, Object>`

And we'll need a 
* `Map<SpimData, Object>` which will be used to store the original data location, a custom name, and so on.

**Comment by martinschorb** [comment]
@NicoKiaru 
I cannot push my new branch, can you check the permissions.

**Comment by NicoKiaru** [comment]
Yes, you should have received an invite now

**Comment by martinschorb** [comment]
works, thanks!

**Comment by martinschorb** [comment]
OK, I think I have gone through the entire UI now, fixing obvious things.

If you like, you can check if I did some stupid mistakes and broke things (renamed variables by accident,...)

Otherwise, if you are OK with the updates, please merge.

**Comment by NicoKiaru** [comment]
Pretty sure this was merged a long time ago. Closing
