### ISSUE TITLE
 edit mode and group mode kill each other

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#140]
Hi,

The BDV window gets locked up and reacts only very delayed when I change between edit mode and group view.

**Comment by NicoKiaru** [comment]
thanks for noting this.

The group mode is kind of messed up. I hope that https://github.com/bigdataviewer/bigdataviewer-core/pull/99 solves it. I have to try

The edit mode also had an independent issue which I adressed yesterday but did not push to the update site yet.

**Comment by NicoKiaru** [comment]
Many it depends on the number of sources displayed - if you have many, the overlay can take a long time to be drawn. Regarding group mode : if the overlay is not in any group, just like any other source, it's not displayed.

If you still have this issue, please ping me @martinschorb , otherwise I'll probably close the issue

**Comment by NicoKiaru** [comment]
Not sure this still happens, closing for now because I have no way to reproduce this easily
