### ISSUE TITLE
Timepoint index arguments when exporting SpimData to XML/HDF5

### ISSUE THREAD

**Issue by ssgpers** [bigdataviewer/bigdataviewer-playground#147]
@NicoKiaru @tischi 

I aim to export my SpimData into xml/HDF5 using this class

https://github.com/bigdataviewer/bigdataviewer-playground/blob/35b1b7bde92367c30b3bdcf2af421450120436d4/src/main/java/sc/fiji/bdvpg/sourceandconverter/exporter/XmlHDF5SpimdataExporter.java#L74

In my current dataset there are no timepoints specified, so I expected `timepointBegin` and `timepointEnd` have to be equal to 0.
When I put these arguments, I get a runtime Error. When I change `timepointEnd` to be equal 1, everything works correctly.

When exporting sources using GUI ( BigDataViewer › Sources › Export Sources to XML/HDF5 Spimdataset), the default arguments are also 0 and 1.

![image](https://user-images.githubusercontent.com/6419504/93473253-15d2c800-f8f6-11ea-9595-4bde26e60bc4.png)

Is it a bug?

**Comment by NicoKiaru** [comment]
Hi @ssgpers , 

Currently the convention is to exclude the last timepoint, and the indexing is 0-based. So that's why the settings should be 0 and 1 to export the only timepoint, of index 0. We should make this clear in the labels of the command.

This convention may not be the best, but it's commonly used in java and python (contrary to matlab : 1-based), so I'm not sure I want to change it. But we could include the timepoint if you think changing the label is not sufficient.

**Comment by tischi** [comment]
@NicoKiaru 

I do not find it intuitive like it is. Since this timepoints must be consecutive, what about:

```
Timepoint (Start)
Timepoints (Number)
```

Then it would be 0 and 1 to only export time point 0.

**Comment by NicoKiaru** [comment]
Nice!

**Comment by ssgpers** [comment]
@NicoKiaru 
Thanks a lot! for clarification
Yes, new labels make sense.
If possible I would suggest to update the names of function arguments or simply add clarifying javadoc comment in the code

**Comment by NicoKiaru** [comment]
I didn't modify this yet, sorry. Next time!
