### ISSUE TITLE
BdvHandle selection UI

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#15]
@NicoKiaru 
Do you have something for people to select a `bdvHandle` via a user interface?
Something like:
```
@Parameter
BdvHandle bdvHandle
```

**Comment by NicoKiaru** [comment]
Yes:

https://imagej.net/Bigdataviewer_Scijava

I spent quite a lot of time understanding 'bigdataviewer_playground' in order to work together with you and @haesleinhuepf and others. It's important to try to be aware of what others do in order to continue in the right way. Your question makes me feel that you didn't do the effort of opening some  of the links I sent you. 

I'm not asking to do things like me, but at least I'd be pleased if you take one hour or two in order to look at what I've done because this is what you asked for and so I did a lot of documentation on my work:

* in the google doc you sent
* in imagej.net (https://imagej.net/Bigdataviewer_Scijava)
* in the repo itself : (https://github.com/BIOP/bigdataviewer_scijava)

There's even a temp update site to avoid the hassle of building it and some video examples.
If you don't spent some time to look at it, how can you know what can be retrieved and what is not worth keeping ?

And it's not like I did not warn I was going to do it: my forum post on this scijava integration dates from November last year (https://forum.image.sc/t/getting-bigdataviewer-instance-in-an-imagej-command/21110)

**Comment by tischi** [comment]
Hi @NicoKiaru,

Thank you for sending the links again! 
We are sorry for not inspecting them in detail!
Also, everything that has to do with SciJava is clearly your expertise! 
We were was just curious whether and how one could add `BdvHandle` as a parameter. 

The hope really was that you would have come to the hackathon! And the idea was that this hackathon would be a great opportunity to educate each other in detail about what we did, which is much easier sitting together for a few days. We were discussing today to try again beginning of next year to meet for 2 days to discuss these things. I think it would be very important, because many of the things that you are doing are overlapping, in my view, quite a lot with what Tobias and Tim-Oliver are doing here at CSBD.

Would you have time for another Skype today to discuss?

**Comment by NicoKiaru** [comment]
Yep I'm missing something  completely agree. I can skype at 17h, would that be ok for a short update ?

For the technical details with Scijava BdvHandle, I'm using this trick discussed on the forum:
https://forum.image.sc/t/displaying-and-using-and-any-object-in-a-scijava-fiji-command/22395
It means you need the class `EasySwingDisplayViewer`, which is in [`scijava-ui-swing`](https://github.com/scijava/scijava-ui-swing/blob/master/src/main/java/org/scijava/ui/swing/viewer/EasySwingDisplayViewer.java) v>0.1.3

After you need to implement two classes: a display (just notifying that this class of object can be displayed) and a viewer, which can be swing or something else. For BdvHandle the class look like this:
* [BdvHandle display](https://github.com/BIOP/bigdataviewer_scijava/blob/master/src/main/java/ch/epfl/biop/bdv/scijava/gui/BdvHandleDisplay.java)
* [BdvHandle display viewer](https://github.com/BIOP/bigdataviewer_scijava/blob/master/src/main/java/ch/epfl/biop/bdv/scijava/gui/swing/SwingBdvHandleViewer.java)

The most important class of the viewer is the one which returns the `JPanel`: [`createDisplayPanel`](https://github.com/BIOP/bigdataviewer_scijava/blob/09fbde9aabc95259e256bd8a446dc63032584833/src/main/java/ch/epfl/biop/bdv/scijava/gui/swing/SwingBdvHandleViewer.java#L122). And each time you have a BdvHandle in a Command which is an input or an output, the [`redraw`](https://github.com/BIOP/bigdataviewer_scijava/blob/09fbde9aabc95259e256bd8a446dc63032584833/src/main/java/ch/epfl/biop/bdv/scijava/gui/swing/SwingBdvHandleViewer.java#L52) function is called. So it can update itself to its new state (sources added for instance).

To facilitate a bit the scripting and handling you can also add a `SingleInputPreprocessor` (see [here](https://github.com/BIOP/bigdataviewer_scijava/blob/master/src/main/java/ch/epfl/biop/bdv/scijava/ActiveBdvPreprocessor.java)) Its job is to feed the BdvHandle object automatically in simple cases (let's say you have only one Bdv window open and your command require one BdvHandle input -> there's no need to specify this input) . Another useful case is that if a command needs a BdvHandle and there's none currently, you can create an empty window one and feed it to the Command.

**Comment by tischi** [comment]
perfect! thanks a lot!!!

**Comment by NicoKiaru** [comment]
If we all agree on https://github.com/haesleinhuepf/bigdataviewer-playground/issues/20 : to keep scijava functionalities out, I think all the ui should be part of a different repo. I can imagine a `bigdataviewer-scijavaui` repo which would use such ui and a `BdvHandle` `Parameter`.

**Comment by NicoKiaru** [comment]
`BdvHandle` as a parameter implemented in commits:

https://github.com/haesleinhuepf/bigdataviewer-playground/commit/c80cec4d2fa6714b87d7aa1c1d050f1dc990f2a2

And BDVSingleton replaced in:

https://github.com/haesleinhuepf/bigdataviewer-playground/commit/76f11235aacdfaf927e96631f5871c277e81793b
