### ISSUE TITLE
Use SciJava logging system

### ISSUE THREAD

**Issue by imagejan** [bigdataviewer/bigdataviewer-playground#172]
I noticed you use `System.out.println()` in `Consumer`s a lot to do logging:

https://github.com/bigdataviewer/bigdataviewer-playground/blob/ccc9240b2943320dda5f4e9b2fc1f2c7ca6aa32c/src/main/java/sc/fiji/bdvpg/scijava/processors/BdvSpimDataPostprocessor.java#L47-L49

How about switching to SciJava's logging system via `LogService#info()`, possibly also with a `Logger` that keeps track of the class producing the log message?

**Comment by NicoKiaru** [comment]
I'm clearly not an expert in this. Do you have a (simple?) example where you would consider the Logging is done in a good way, @imagejan ?

**Comment by imagejan** [comment]
@NicoKiaru if you have a `Logger` parameter in your command, you can just call `Logger#info()` or `Logger#error()` as required:

```java
@Parameter
private Logger logger;

...

logger.error("Something went wrong.");
```

---


If you can't have a `Logger` because you're not in a `Command` or similar, you can still use `LogService` via the `Context`, I guess:

```java
context.service(LogService.class).error("Something went wrong.");
```

**Comment by NicoKiaru** [comment]
@imagejan I went for slf4j logging instead of scijava logservice, because I did not have access to s scijava context in all classes...

But clearly that was really helpful to find a super annoying GUI bug in bdv...

@tischi there are now a lot of logs showing up. But they can be deactivated with `DebugTools`, the same way you deactivate them with bioformats. You can set the level of logging and also probably restrict the logging to certain classes.
