### ISSUE TITLE
Model source for resampling

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#177]
@NicoKiaru 

I was looking through the code for this request: https://forum.image.sc/t/resample-3d-data-along-a-plane-and-convert-to-ij1-imageplus/49961

Because I think we could add a `BdvPlaygroundActionCommand` that does what @manerotoni needs.

But I do not understand the point of the `SourceAndConverter model`; you say it "defines the portion of space sampled". 
If that is the only thing it does would it be an option to replace this by a `RealInterval`?
Then the user could specify the region using a `TransformedBoxOverlay`.

And to get the `RealInterval` from a model, if needed, we can use:

```
public static FinalRealInterval estimateBounds( Source< ? > source )
{
	final AffineTransform3D affineTransform3D = new AffineTransform3D();
	source.getSourceTransform( 0, 0, affineTransform3D );
	final FinalRealInterval bounds = affineTransform3D.estimateBounds( source.getSource( 0, 0 ) );
	return bounds;
}
```

```
/**
     * Constructor where the region and sampling is defined by a model source
     * This constructor translates information from the model source into
     * an affine transform and a number of voxels
     * @param name name of the source
     * @param model model source and converter : defines the portion of space sampled
     * @param timePoint timepoint of the model chosen for the model
     * @param voxSizeX overrides the model voxel size for a new one  - in bdv current units (x)
     * @param voxSizeY overrides the model voxel size for a new one - in bdv current units (y)
     * @param voxSizeZ overrides the model voxel size for a new one - in bdv current units (z)
     */
    public EmptySourceAndConverterCreator(
            String name,
            SourceAndConverter model,
            int timePoint,
            double voxSizeX, double voxSizeY, double voxSizeZ
```

**Comment by NicoKiaru** [comment]
Hi tischi,

The reason behind using SourceAndConverter is multiple:
* it behaves like any source, thus for instance, it can be moved in space using manual transform. It can also be seen in the editor mode, even if it's empty. We could make it a grid source by default (functional source), so that the user could directly see the size of the pixels.
* also there's a serialization mechanism in bdv playground which allows to store SourceAndConverter directly (as a json file), even if it's not a SourceAndConverter from a SpimData object. So you can store your 'resampling model' easily
* last, and it's probably the most important one : sometimes you want to resample a SourceAndConverter not from an empty source that you have to define manually, but directly from another acquisition, which is already a SourceAndConverter. For instance in correlative EM Fluo, you can directly ask to resample the fluo image 'like' the EM image, or vice versa. 

But you can make a static function which does the same thing with different input arguments. You'll just have to go through the SourceAndConverter mechanism only in the static function, and it will be invisible outside.

The transformed box overlay is very cool, but for these reason I would output a SourceAndConverter from it rather than a RealInterval.

Also, for your RealInterval, you need to have it positioned in space, so linked to an affine transform, right ? Because having the bounds in each dimension is not sufficient if you need to rotate it in space. SourceAndConverter thus provides a way to link an affine transform and a RealInterval.

**Comment by tischi** [comment]
Very interesting! I did not think of it like this!

Let's say I have a RealInterval (e.g. from a TransformedBoxOverlay), how would I make a SourceAndConverter from it?

Maybe something to be implemented?

Would this be the correct signature?
```
SourceAndConverterHelper.createEmptySourceAndConverter( RealInterval realInterval, double[] voxelSpacing, int numTimepoints );
```

**Comment by NicoKiaru** [comment]
I think, so, and maybe one with an optional AffineTransform argument (it really looks like the signature of BdvFunctions.show)

**Comment by tischi** [comment]
OK!

Should I work on this? I think it would be good to have, isn't it?

**Comment by NicoKiaru** [comment]
Sure, you can have a look at https://github.com/bigdataviewer/bigdataviewer-playground/blob/master/src/main/java/sc/fiji/bdvpg/scijava/command/source/NewSourceCommand.java if you wish. And maybe do something with the bdv overlay ? Up to you!

**Comment by tischi** [comment]
I will work on it. I think this could be a quite relevant use case.

**Comment by manerotoni** [comment]
Great! Thanks a lot that you already thinking about such a feature.

**Comment by NicoKiaru** [comment]
@tischi I think I'll give a try to improve what I have in bdv-biop-tools. I won't use the box overlay, butI'll simplify

https://github.com/BIOP/bigdataviewer-biop-tools/blob/master/src/main/java/ch/epfl/biop/bdv/command/exporter/BdvViewToImagePlusExportCommand.java  with 'ok' default parameters (there are too many in this one)

**Comment by tischi** [comment]
@NicoKiaru 

Ok, Great, but should we still implement this?

```
SourceAndConverterHelper.createEmptySourceAndConverter( RealInterval realInterval, double[] voxelSpacing, int numTimepoints, AffineTransform affineTransform );
```

I think you could also use it from within: https://github.com/BIOP/bigdataviewer-biop-tools/blob/master/src/main/java/ch/epfl/biop/bdv/command/exporter/BdvViewToImagePlusExportCommand.java

And then we would avoid code duplication.

**Comment by NicoKiaru** [comment]
Yep, that should nicely replace this : 

https://github.com/BIOP/bigdataviewer-biop-tools/blob/aecf8ca49da9097b46b7b933a6869892b72d0dd1/src/main/java/ch/epfl/biop/bdv/command/exporter/BdvViewToImagePlusExportCommand.java#L189

I'm not sure about timepoints. I think it's infinite number of timepoints by default

**Comment by NicoKiaru** [comment]
I added a simple example of the resampling mechanism here : https://github.com/bigdataviewer/bigdataviewer-playground/blob/master/src/test/src/sc/fiji/bdvpg/SimpleResamplingDemo.java

And added constructors in order to build more easily 'empty' source and converters in https://github.com/bigdataviewer/bigdataviewer-playground/commit/e01ee55137e42bc1cf3d153612c97acf3f119019

Please reopen if needed
