### ISSUE TITLE
ConverterChanger code question

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#185]
In your version of the `ConverterChanger` you require two inputs, one for the volatile converter and one for the other one. [EDIT]: Do you have an example where you create them? In other words do I actually need to build two different converters?

**Comment by NicoKiaru** [comment]
Here is an example : https://github.com/bigdataviewer/bigdataviewer-playground/blob/ffa8c41bf8f1a7f6ceefd4adabeef8c6f8a14ee3/src/main/java/sc/fiji/bdvpg/scijava/command/source/LUTSourceCreatorCommand.java#L76

A LUT is applied to a current source.

I'm not sure about this, these Converter are tricky to implement in an efficient way, see the gitter discussion with @tpietzsch 

And maybe Tobias can enlighten us on your question ?

(Also I have no time today Christian sorry)

**Comment by tischi** [comment]
For me, it seems to work with just one converter:

```
@Override
public void convert( RealType input, ARGBType output )
{
	if ( input instanceof Volatile )
	{
		if ( ! ( ( Volatile ) input ).isValid() )
		{
			output.set( 0 );
			return;
		}
	}
        // .... do the actual conversion
}
```

**Comment by NicoKiaru** [comment]
Yes, but then you perform two checks per pixel. I don't know if this has an influence, Maybe make a constructor with only one converter which duplicates (or not?) it and calls the other constructor with two parameters. This lets the possibility to provide 2 constructors just in case

**Comment by tischi** [comment]
> Yes, but then you perform two checks per pixel. I don't know if this has an influence,

I did not see an obvious performance issue with this code, it is just an `if` statement, I would hope that's not too bad.

> Maybe make a constructor with only one converter which duplicates (or not?) it and calls the other constructor with two parameters. 

I think for this constructor we would need to require a `Converter< ? extends RealType, ARGBType >`, because we need something that covers both Volatile and NonVolatile and that covers the numeric types. I think `? extends RealType` is not bad for this; but I am not sure what I am doing here; I can however say that it works in practice for me. So, yeah, if you don't mind I would add another constructor with only one converter.

**Comment by tpietzsch** [comment]
The second converter is used when a source has both volatile and non-volatile versions and the non-volatile version is used.
This happens for example if you record a movie. In this case, using the volatile version would not be good, because in the movie you want all data to be present obviously.

Probably, the `instanceof` check is optimistically assumed to always be `true`, until the other case occurs.
I would expect that you see a slowdown after you record a movie.

Additionally, there is the issue discussed here https://gitter.im/bigdataviewer/bigdataviewer-core?at=6058c6c02beb1e1da3c2f187
I would expect to see additional slowdown if the same converter (class) is used for different `RealType`s.

**Comment by NicoKiaru** [comment]
@tischi I think it's not a problem in the end. If you want to use the same converter for volatile and no volatile, you can do it. And if one wants to specify different ones or performance, it's also possible
