### ISSUE TITLE
BrightnessAutoAdjuster works with services

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#222]
@NicoKiaru 

I found the following change in the `BrightnessAutoAdjuster`:

```
		//minMaxGroup.getMinBoundedValue().setCurrentValue( min );
		//minMaxGroup.getMaxBoundedValue().setCurrentValue( max );
		ConverterSetup converterSetup = SourceAndConverterServices.getSourceAndConverterDisplayService().getConverterSetup( sac );
		converterSetup.setDisplayRange(min, max);
```

This crashes if the `getSourceAndConverterDisplayService()` returns null and thus this class cannot be used outside the Service context. Could we revert this back such that the commented lines are used again? If possible, I think we should not have the Services logic inside of such classes, but this should be handled by the calling instances, which I guess are the `Commands`. We could however give an optional `List< bdvHandle >` in the constructor such that existing `converterSetups` could be found and adjusted. For example the `ViewerTransformAdjuster` works like this. I think it would be great to implement the same logic also for the `BrightnessAutoAdjuster`.

What do you think?

**Comment by NicoKiaru** [comment]
For viewer adjusters, it makes sense to have bdvs because you need to adjust a viewer. The thing about convertersetups is that they can live fully outside bdvs, (these values are stored within abstractspimdata for instance). 

But to push this logic further, I think it would make sense to put convertersetup methods into the sourceandconverter service directly, which should also solve this problem.

Ideally a convertersetup could be shared within several bdvs and even sciview for instance.

**Comment by tischi** [comment]
> But to push this logic further, I think it would make sense to put convertersetup methods into the sourceandconverter service directly, which should also solve this problem.

That sounds good! As a first step, to me that simply would mean that the code that currently calls the `BrightnessAutoAdjuster` would be responsible for adjusting the `ConverterSetups` rather than the `BrightnessAutoAdjuster` itself. Or is it more complex than that?

**Comment by NicoKiaru** [comment]
But to 'autoadjust', you need a source, no ? How can you adjust using only convertersetups ? Maybe I'm misunderstanding

**Comment by tischi** [comment]
I think I wrote it badly. 

I would suggest:

`BrightnessAutoAdjuster(sac)` adjusts the converter and has methods `getMin()`, `getMax()`.

Other code deals with the `ConverterSetups`, consuming the output of the `BrightnessAutoAdjuster`.

**Comment by NicoKiaru** [comment]
Ah right, I was confused about what's in the converter and what's in the convertersetup. I see

**Comment by NicoKiaru** [comment]
Was something done for this issue finally @tischi ?

**Comment by tischi** [comment]
Nope, I don't think so yet. I would have to dig into this again as I forgot what the issue was.

**Comment by NicoKiaru** [comment]
I put the convertersetup accessible in the SourceAndConverterService as you suggested initially. The problem with converters is that they are not always having a getmin and getmax function, while converter setups have.

I increase the version number '0.4+' because this modifies the service interface.
