### ISSUE TITLE
Choices of auto-contrast and adjust viewer transform are not macro recorded.

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#226]
It only records:

```
run("MRI Stack");
run("Get Sources From ImagePlus");
run("BDV - Create empty BDV window");
```

**Comment by NicoKiaru** [comment]
Yes, it's because it's in the supplier now. The command `BdvWindowCreatorCommand` has not argument:

`
public class BdvWindowCreatorCommand implements BdvPlaygroundActionCommand {

    /**
     * This triggers: {@link sc.fiji.bdvpg.scijava.processors.BdvHandlePostprocessor}
     */
    @Parameter(type = ItemIO.OUTPUT)
    public BdvHandle bdvh;

    @Parameter
    SourceAndConverterBdvDisplayService sacDisplayService;

    @Override
    public void run() {
        bdvh = sacDisplayService.getNewBdv();
    }

}
`

You can/should create another command if you want a specific bdvhandle, or override the default supplier in the display service. It has changed because of the modularization of the bdv windows supplied.
