### ISSUE TITLE
Check new bdv-core

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-playground#70]
@NicoKiaru 
https://forum.image.sc/t/improved-ui-for-handling-many-sources-in-bigdataviewer/33060

We should make a branch `newBdvCore` and check what happens :-)

**Comment by NicoKiaru** [comment]
Indeed!

https://github.com/bigdataviewer/bigdataviewer-core/pull/68

**Comment by NicoKiaru** [comment]
I tested very quickly with the new `bigdataviewer-core`. And we cannot do much yet. For now it's hanging forever on startup, with a window open, but not responsive.

Maybe it's because `bigdataviewer-vistools` is not adapted yet. We depend very little on it, yet we depend on vistools for the initial creation of an empty Bdv window.

But with your question in the thread bigdataviewer/bigdataviewer-core#68 I realized that we do not need so much vistools. So an option would be to get  rid of it completely ? But it's pretty annoying because we wrote everything with `BdvHandle`. So I'll wait for now.

**Comment by tischi** [comment]
@NicoKiaru 
Maybe we should not use vis tools but "create our own `bdv`". 
See the discussion here: https://github.com/bigdataviewer/bigdataviewer-core/pull/68
(Currently quite at the bottom of the thread)

**Comment by NicoKiaru** [comment]
I pushed a `newBdvCore` branch, but there are minor adaptations for the moment, and apart from compiling, it does not do much:

Also, it needs to have the new bdv core jar accessible from the branch `table-tree-cards-clean`

**Comment by NicoKiaru** [comment]
It works approximately. Many things are broken, but mainly in the service, which hopefully will be much more simple once rewritten because the indexing logic which was hidden has disappeared.

Good thing is that actions involving SourceAndConverter have not been modified at all.

Everything revolving around `ConverterSetup` has to be checked and modified

Among current broken things:
* BdvCreator : options is disabled for now (no custom projector thus)
* Screenshot : indexing logic was too deep into it
* ClickBehaviourInstaller : I can't find where are triggerbindings

**Comment by tischi** [comment]
> BdvCreator : options is disabled for now (no custom projector thus)

I think I mentioned it somewhere else already, but, maybe we anyway should consider using just `bdv-core` without `bdv-vistools`, because our UI together with the new UI from Tobias (as nice as it is) might overload the users. 

I think we might only need  to instantiate a `ViewerFrame`, see here: 
https://github.com/bigdataviewer/bigdataviewer-core/blob/b9e308b70afb1addf3ffb8c5199d2db45f55cde1/src/main/java/bdv/BigDataViewer.java#L333

The `accumulateProjector` would be set using the `ViewerOptions`.

What do you think?

**Comment by NicoKiaru** [comment]
In the new branch I've used `BigDataViewer` objects directly and got rid of `BdvHandle`. We could use `ViewerFrame` directly but I do not see the advantage of it. The new UI is almost perfectly compatible with what we have now (the wrapping with TransformedSource is the little difference), and it's quite hidden.

> The accumulateProjector would be set using the ViewerOptions.

Yes, and it can be set with Bigdataviewer constructor as well. The reason it's not done currently is because I was working on the core aspects first. I will probably modify it now.

When you have time to work back on playground, it would be good if you can fix the screenshot action in newBdvCore. Also it you want to advance the rightClickBehaviour branch there are several things that need to be done:
* merge the master into rightClickBehaviour (can you do it ?)
* when everything's alright, merge rightClickBehaviour into master
* then try to merge it within newBdvCore

We need to keep the master right at the moment because we do not know when the new ui will be deployed. So, we should try to follow these rules, whenever possible:

* for everything related to actions improvement or new action : work on master and derived branch, 
* when a modification is ok in the master, merge it with newBdvCore (like the right click behaviour)
* for everything related to the new core of bdv only: work on newBdvCore

Let me know if that sounds right

Also you can have a look at SourceAndConverterDisplayService : with the new core it's much much more simple.

**Comment by tischi** [comment]
> In the new branch I've used BigDataViewer objects directly and got rid of BdvHandle. We could use ViewerFrame directly but I do not see the advantage of it. The new UI is almost perfectly compatible with what we have now (the wrapping with TransformedSource is the little difference), and it's quite hidden.

OK. Let's try to use his UI!

> merge the master into rightClickBehaviour (can you do it ?)

done.

> when everything's alright, merge rightClickBehaviour into master

could you do it?

> when a modification is ok in the master, merge it with newBdvCore (like the right click behaviour)

that means merge the current **master** into **newBdvCore**, right?

> Also you can have a look at SourceAndConverterDisplayService : with the new core it's much much more simple.

looks good indeed :-)

**Comment by NicoKiaru** [comment]
> that means merge the current master into newBdvCore, right?

Honestly that's where I'm the least comfortable. I don't know if we will be able to keep to two separate branches cleanly. Maybe this will require to write some tests ?

> when everything's alright, merge rightClickBehaviour into master

I'm looking at that.

Last newbdvcore commit already restored the mixed projection

**Comment by NicoKiaru** [comment]
Switch to new state and ui in https://github.com/bigdataviewer/bigdataviewer-playground/commit/3439fc9fd43550de69ed30c4886886f368b1e837
