### ISSUE TITLE
scale bar

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#76]
Hi,

could we have a dynamically adapting scale bar?

The ImageJ > Analyze > Tools > Scalebar functionality would be perfect to generate it. Instead of "Width in microns" something like "x% of the viewer window width" and then automatically adapting it to the zoom level would be amazing.

**Comment by NicoKiaru** [comment]
Would be awesome indeed. One thing is that we need to specifiy what is the unit of the bdv window when creating it and finding a way to attach this info to the window

**Comment by tischi** [comment]
>  Instead of "Width in microns" something like "x% of the viewer window width" and then automatically adapting it to the zoom level would be amazing.

That exists already and is easy to add:

```
Prefs.showScaleBar( true );
Prefs.scaleBarColor( ARGBType.rgba( 255, 255, 255, 255 ) );
```

@NicoKiaru Shall I add it to our code? This is however a global setting. I am not sure how one can specify for a single `bdv` instance whether it should have a scale bar or not.

> what is the unit of the bdv window

That is indeed a good one! Because, in fact, the way the `xml`s are currently parsed assumes that all sources have the same unit! In other words, the units are entirely and implicitly specified by the `<affineTransform>` in the `xml`.  I think that is kind of an issue...
@NicoKiaru correct me if I'm wrong

**Comment by NicoKiaru** [comment]
I dropped the ball here. Yeah let's make this global and then make a Command for settings these preferences. If the prefs are modular enough, we could probably add the default projection mode here and save us a few clicks.

**Comment by NicoKiaru** [comment]
It's now possible to enable or disable scalebars with this Command:

https://github.com/bigdataviewer/bigdataviewer-playground/blob/master/src/main/java/sc/fiji/bdvpg/scijava/command/bdv/BdvSettingsCommand.java


Located in FIJI in `Bdv>Set Bindings`
