### ISSUE TITLE
bookmarks across bdv windows

### ISSUE THREAD

**Issue by martinschorb** [bigdataviewer/bigdataviewer-playground#83]
Would it be possible to make bookmarks available for different windows.
Could they be shown along the sources in the list? Maybe even stored as separate xml?

**Comment by NicoKiaru** [comment]
Bookmarks for what ? Current view of Bdv ?

**Comment by martinschorb** [comment]
Exactly, the ```Shift+B+XX``` functionality. I think this is coupled to the current viewer window, isn't it?

**Comment by NicoKiaru** [comment]
Yep. I think so. I do not have time to propose something. Maybe @tischi has, but not sure.

Otherwise, here's a workaround:
* using the function as it exists now
* use the synchronize views function to apply the transformation to all bdv windows

What I could add is a 'pause' function in the window that controls view synchronizer, if you think that's useful.

What do you think ?

**Comment by NicoKiaru** [comment]
The workaround (sync views + bookmarks) is working. Please reopen if you think that's not enough
